### ISSUE TITLE
what is the difference between fun(x,y) and  fun(y,x) when using dblquad

### ISSUE THREAD

**Issue by liushang0322** [aurelio-amerio/MultiQuad.jl#8]
When using qblquad, it seems that the order of the x and y passed in when the function is created is very important. What is the principle of this?

**Comment by aurelio-amerio** [comment]
Hello, in general the order of integration matters, i.e. \int f(y,x) dx dy is different from \int f(x,y) dy dx. In many cases (when the bounds are fixed and not functions) you can exchange the integration order, but we must remain as general as possible. 

Taking that in consideration, one has to choose a convention for the function signature, since the order of the positional arguments in a function matters. Loosely following the [scipy dblquad convention](https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/generated/scipy.integrate.dblquad.html), I decided to define the function such that  for f(y,x), we will first integrate in x and then in y. The idea is that you always integrate first on the rightmost varible. 

Does this make more sense to you?

**Comment by liushang0322** [comment]
> 

Thank you very much for your reply, my purpose is to confirm with you whether it is consistent with the pattern I found, it seems to be the case now, it should be no problem, thank you again
